#!/usr/bin/env python3
"""QJC Hermes 자동화 cron job 일괄 등록기.

9개 자동화 중 cron 스케줄이 있는 8개를 cron.jobs.create_job 으로 등록한다.
(휴머나이저는 on-demand 스킬이므로 cron 없음.)

- dry-run 이 기본. 실제 등록은 --apply.
- idempotent: 동일 name 이 이미 있으면 skip. --force 시 삭제 후 재등록.
- deliver 는 콜론 없는 플랫폼명만 사용 → scheduler 가 {PLATFORM}_HOME_CHANNEL
  환경변수로 자동 폴백한다. chat_id 를 jobs.json 에 하드코딩하지 않는다.

사용 예:
    python scripts/register_automations.py            # dry-run (등록 예정 출력)
    python scripts/register_automations.py --apply     # 실제 등록
    python scripts/register_automations.py --apply --force   # 기존 삭제 후 재등록
    python scripts/register_automations.py --remove    # 'auto:' job 전체 삭제
"""

import argparse
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from cron.jobs import create_job, list_jobs, remove_job
from hermes_constants import get_hermes_home

NAME_PREFIX = "auto:"


def _script(rel: str) -> str:
    """프로젝트 루트 기준 수집 스크립트의 절대 경로."""
    return str(PROJECT_ROOT / rel)


def _make_wrapper(skill: str, target_abs: str) -> str:
    """~/.hermes/scripts/auto/{skill}.py 래퍼를 만들고 cron 기준 상대경로를 반환.

    cron(scheduler._run_job_script)은 script 가 HERMES_HOME/scripts/ 안에 있어야만
    실행한다 (path.resolve() 후 검사 — symlink 불가). 그래서 scripts 디렉토리 안에
    실제 래퍼 파일을 두고, runpy 로 프로젝트의 collect.py 를 실행한다.
    """
    auto_dir = get_hermes_home() / "scripts" / "auto"
    auto_dir.mkdir(parents=True, exist_ok=True)
    wrapper = auto_dir / f"{skill}.py"
    wrapper.write_text(
        "#!/usr/bin/env python3\n"
        "# AUTO-GENERATED by register_automations.py — 수정하지 마세요.\n"
        "# cron 가드(HERMES_HOME/scripts 제한)를 통과하기 위한 얇은 래퍼.\n"
        "import runpy\n"
        f"runpy.run_path({target_abs!r}, run_name='__main__')\n",
        encoding="utf-8",
    )
    try:
        os.chmod(wrapper, 0o700)
    except OSError:
        pass
    return f"auto/{skill}.py"  # HERMES_HOME/scripts/ 기준 상대경로


# deliver: telegram/discord = {PLATFORM}_HOME_CHANNEL 폴백, local = 전송 없음(파일 저장형)
AUTOMATIONS = [
    {
        "name": f"{NAME_PREFIX}daily-brief",
        "skill": "daily-brief",
        "schedule": "0 7 * * *",
        "deliver": "telegram",
        "script": _script("skills/feeds/daily-brief/scripts/collect.py"),
        "prompt": (
            "daily-brief 스킬 지침에 따라 아침 데일리 브리프를 작성하라. "
            "주입된 수집 데이터(캘린더/긴급 메일/날씨/헤드라인)를 한 번에 스캔 가능한 "
            "하나의 한국어 메시지로 정리해 전송하라. 새 일정·메일이 전혀 없으면 [SILENT]."
        ),
    },
    {
        "name": f"{NAME_PREFIX}trend-radar",
        "skill": "trend-radar",
        "schedule": "0 8 * * *",
        "deliver": "telegram",
        "script": _script("skills/feeds/trend-radar/scripts/collect.py"),
        "prompt": (
            "trend-radar 스킬 지침에 따라, 주입된 트렌딩 데이터를 분석해 지난 24시간 동안 "
            "속도가 붙은 AI 워크플로우 5개를 콘텐츠 앵글로 랭킹해 한국어로 전달하라."
        ),
    },
    {
        "name": f"{NAME_PREFIX}meeting-brief",
        "skill": "meeting-brief",
        "schedule": "*/30 * * * *",
        "deliver": "telegram",
        "script": _script("skills/productivity/meeting-brief/scripts/collect.py"),
        "prompt": (
            "meeting-brief 스킬 지침에 따라, 주입된 데이터에 30~60분 내 시작하는 미팅이 있으면 "
            "참석자 컨텍스트와 최근 메일 스레드를 1페이지 한국어 브리프로 정리해 전송하라. "
            "임박한 미팅이 없으면 [SILENT]."
        ),
    },
    {
        "name": f"{NAME_PREFIX}support-triage",
        "skill": "support-triage",
        "schedule": "0 9 * * *",
        "deliver": "discord",
        "script": _script("skills/productivity/support-triage/scripts/collect.py"),
        "prompt": (
            "support-triage 스킬 지침에 따라, 주입된 인박스 데이터에서 지원 티켓을 이슈 유형별로 "
            "분류해 Discord 회사 채널에 로그하라. 월요일이면 주간 top5 반복 이슈도 함께 보고하라."
        ),
    },
    {
        "name": f"{NAME_PREFIX}weekly-business",
        "skill": "weekly-business",
        "schedule": "0 9 * * 1",
        "deliver": "telegram",
        "script": _script("skills/productivity/weekly-business/scripts/collect.py"),
        "prompt": (
            "weekly-business 스킬 지침에 따라, 주입된 주간 지표(매출/구독/콘텐츠/팔로워/환불)를 "
            "지난주 대비(WoW) 단일 한국어 대시보드로 정리해 전송하라."
        ),
    },
    {
        "name": f"{NAME_PREFIX}swipe-file",
        "skill": "swipe-file",
        "schedule": "0 2 * * *",
        "deliver": "local",
        "script": _script("skills/social-media/swipe-file/scripts/collect.py"),
        "prompt": (
            "swipe-file 스킬 지침에 따라, 주입된 고성과 게시물에서 훅/구조/주제/오프닝/통계를 "
            "추출해 Obsidian 볼트의 Swipe File 에 구조화 저장하라. 새 항목이 없으면 [SILENT]."
        ),
    },
    {
        "name": f"{NAME_PREFIX}bookmark-inbox",
        "skill": "bookmark-inbox",
        "schedule": "0 */6 * * *",
        "deliver": "local",
        "script": _script("skills/social-media/bookmark-inbox/scripts/collect.py"),
        "prompt": (
            "bookmark-inbox 스킬 지침에 따라, 주입된 신규 북마크를 3개 불릿으로 요약하고 자동 태깅해 "
            "Obsidian 볼트의 Bookmarks 에 주제별로 파일링하라. 새 북마크가 없으면 [SILENT]."
        ),
    },
    {
        "name": f"{NAME_PREFIX}second-brain",
        "skill": "second-brain",
        "schedule": "0 3 * * *",
        "deliver": "local",
        "script": _script("skills/note-taking/second-brain/scripts/build_moc.py"),
        "prompt": (
            "second-brain 스킬 지침에 따라, 주입된 볼트 인덱스를 검토하고 MOC(Map of Content)와 "
            "오펀 노트/태그 정합성을 점검하라. 조치가 필요 없으면 [SILENT]."
        ),
    },
]


def _existing_auto_jobs() -> dict:
    return {
        j.get("name"): j
        for j in list_jobs()
        if str(j.get("name", "")).startswith(NAME_PREFIX)
    }


def cmd_remove() -> int:
    existing = _existing_auto_jobs()
    if not existing:
        print("삭제할 'auto:' job 없음.")
        return 0
    for name, job in existing.items():
        remove_job(job["id"])
        print(f"삭제됨: {name} (id={job['id']})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="QJC Hermes 자동화 cron job 등록")
    parser.add_argument("--apply", action="store_true", help="실제 등록 (기본은 dry-run)")
    parser.add_argument("--force", action="store_true", help="기존 동일 name 삭제 후 재등록")
    parser.add_argument("--remove", action="store_true", help="'auto:' job 전체 삭제")
    args = parser.parse_args()

    if args.remove:
        return cmd_remove()

    # 근본 방어: cron job 의 skill 은 HERMES_HOME/skills/ 에서 로드된다(skills_tool.SKILLS_DIR).
    # 프로젝트 skills/ 에서만 만들고 sync 를 안 하면 런타임이 "Skill not found" 로 실패한다.
    # 등록 직전 표준 배포 도구로 sync 하여 스킬·cron·래퍼가 항상 함께 배포되도록 보장.
    if args.apply:
        from tools.skills_sync import sync_skills
        sr = sync_skills(quiet=True)
        print(f"스킬 배포(~/.hermes/skills/): {len(sr.get('copied', []))} new, "
              f"{len(sr.get('updated', []))} updated, "
              f"{len(sr.get('user_modified', []))} user-modified 보존\n")

    existing = _existing_auto_jobs()
    registered = skipped = 0

    for auto in AUTOMATIONS:
        name = auto["name"]
        exists = name in existing

        if exists and not args.force:
            print(f"SKIP (이미 존재): {name}")
            skipped += 1
            continue

        if not args.apply:
            tag = "재등록 예정" if exists else "등록 예정"
            print(f"[dry-run] {tag}: {name} | {auto['schedule']} | deliver={auto['deliver']}")
            registered += 1
            continue

        if exists and args.force:
            remove_job(existing[name]["id"])

        # cron 가드 통과용 래퍼를 HERMES_HOME/scripts/auto/ 에 생성하고 그 상대경로를 등록.
        script_ref = _make_wrapper(auto["skill"], auto["script"]) if auto.get("script") else None

        job = create_job(
            prompt=auto["prompt"],
            schedule=auto["schedule"],
            name=name,
            skill=auto["skill"],
            script=script_ref,
            deliver=auto["deliver"],
        )
        print(f"등록됨: {name} (id={job['id']}) | next={job.get('next_run_at')}")
        registered += 1

    mode = "등록" if args.apply else "dry-run"
    print(f"\n{mode} 완료: {registered}건 처리, {skipped}건 skip "
          f"(전체 {len(AUTOMATIONS)}개 자동화).")
    if not args.apply:
        print("실제 등록하려면 --apply 를 붙여 다시 실행하세요.")
        print("전송 대상: TELEGRAM_HOME_CHANNEL / DISCORD_HOME_CHANNEL 환경변수 설정 필요.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
